<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../Common.props" />

  <PropertyGroup>
    <OutputType>exe</OutputType>
    <AssemblyName>Editor</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Shared/Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hexa.NET.ImGui" Version="2.2.9" />
    <PackageReference Include="Hexa.NET.ImGui.Backends" Version="1.0.18" />
    <PackageReference Include="Hexa.NET.ImGui.Backends.SDL3" Version="1.0.18" />
    <PackageReference Include="Hexa.NET.ImGuizmo" Version="2.2.9" />
    <PackageReference Include="Hexa.NET.ImPlot" Version="2.2.9" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0" />
  </ItemGroup>

  <!-- include resources the editor needs -->
  <ItemGroup>
    <Content Include="_Resources/**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <!-- include the source code for building a player with the editor -->
  <ItemGroup>
    <Content Include="../Platform/**" Exclude="../Platform/bin/**;../Platform/obj/**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>_Resources/SourceForGameBuilding/Platform/%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
    <Content Include="../Shared/**" Exclude="../Shared/bin/**;../Shared/obj/**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>_Resources/SourceForGameBuilding/Shared/%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
    <Content Include="../Player/**" Exclude="../Player/bin/**;../Player/obj/**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>_Resources/SourceForGameBuilding/Player/%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
    <Content Include="../Common.props">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>_Resources/SourceForGameBuilding/Common.props</Link>
    </Content>
  </ItemGroup>

</Project>